### ISSUE TITLE
Typo / TL Error Reports

### ISSUE THREAD

**Issue by Aspirety** [07th-mod/higurashi-console-arcs#5] opened 2017-06-19 11:56 UTC
I guess I'll post stuff here as I come across it.

![](http://puu.sh/wom1L/4c66794dc3.jpg)

The 別に here in response to "are you feeling sick?" is translated as "Besides..." pretty sure it should be "Not really..."

**Comment by ItaloKnox** [comment] 2017-06-19 11:58
I'll assign this to @DoctorDiablo since it's his work but I'll pass by every now and then to check if the issues were solved.

**Comment by Aspirety** [comment] 2017-06-19 12:03
![](http://puu.sh/womgP/673ced3a6b.jpg)

Not sure what to make of this, seems like an issue with italics. I never noticed anything like it in previous releases. (Did previous arcs even have any italics?)

**Comment by enumag** [comment] 2017-06-19 12:06
@Aspirety No other arcs don't use italics (or very very rarely). In my opinion we should remove it here as well.

**Comment by DoctorDiablo** [comment] 2017-06-19 13:33
The italics are there because the original text had her name emphasized using Japanese style square quotes 『佐伯』さん which I converted to italics in most cases.  The main chapters don't use italics very often, but the writers for these arcs really love square quotes so you'll see it fairly often.

In this case though, it trashes the kerning so it's probably better to remove the italics here.

**Comment by Aspirety** [comment] 2017-06-20 06:37
![](http://puu.sh/wp9Zw/dd67622b8b.jpg)

I see what you were going for here but it just looks awkward ^^;

**Comment by Aspirety** [comment] 2017-06-20 07:03
![](http://puu.sh/wpaOu/242a8302c4.jpg)
「いい加減にしてください…」 here should probably be translated as "Cut it out..." or "Give it a rest...", instead of this.

![](http://puu.sh/wpaQQ/46ad6551f6.jpg)
This TL also seems a bit odd. I'd personally translated it as "But... I was opposed... to the decision to leave Hinamizawa. I told you I didn't want to."

**Comment by Aspirety** [comment] 2017-06-20 15:07
![](http://puu.sh/wpsxv/1550640479.jpg)

Should probably change this to "blue".

**Comment by enumag** [comment] 2017-06-20 15:11
> "Old Guy" here is actually an old woman.

Please report naming issues [here](https://github.com/07th-mod/higurashi-patch-compiler/issues/2#issuecomment-309732274), those are for me.

**Comment by Aspirety** [comment] 2017-06-20 17:52
![20170621034718_1](https://user-images.githubusercontent.com/10488699/27347730-f41ca5f8-5634-11e7-85c1-cce295edd0e2.jpg)

Lastly, I hope you'll consider picking a different front for this section ^^;

Despite some errors, really enjoyed my readthrough! You guys have done a supurb job of bringing this chapter to English-speaking audiences. Can't wait for the next one!

Also, am I correct in assuming there's no tips for this arc?

**Comment by DoctorDiablo** [comment] 2017-06-20 22:46
Nice.  I checked in fixes for all of these issues, except for the font in the credits.  I agree that the font isn't that great, but the text is actually stored in one huge image file so to change the font I'd have to retype all the text and reposition each line.  I might end up doing that anyway, but no promises yet!

There actually are a couple tips for this arc, but it's difficult to include them because of limitation of the engine MangaGamer is using.  All the logic that controls the tips is hard-coded, so we don't have direct access to it.  I'd love to include the tips, but I have no idea if it's even possible.

**Comment by enumag** [comment] 2017-06-21 04:11
@DoctorDiablo In my opinion we should add a yes/no choice whether to play scripts at the end of each chapter that unlocks any of them. If yes is selected then play them using CallScript. Same for the omake if it exists.

**Comment by Aspirety** [comment] 2017-06-21 06:19
That's not a bad idea! In the worst case you could always just include them as a text file. I'm guessing you haven't translated them yet?

**Comment by Aspirety** [comment] 2017-06-21 10:28
Oh there was also this.

![](http://puu.sh/wqj6Q/dc30ca3134.jpg)

The indentation seems odd.

**Comment by Aspirety** [comment] 2017-06-21 10:38
I'm also unsure whether we should go with 'Toudou' or 'Akira' for his name. I'm pretty sure he's called Toudou by most people early in the story? But in the end he's called Akira.

**Comment by DoctorDiablo** [comment] 2017-06-21 13:26
I was so fixated on getting MG's tips interface to work that I never even considered just calling the tips directly from the main script.  That's a good idea.  I need to find where the text for those is actually stored.  And I'll have to translate them, which will probably take me a week (I'm slow).  But I think it's totally doable!

**Comment by Aspirety** [comment] 2017-06-21 17:23
Oh just found another typo.

![](http://puu.sh/wqA2E/27d9dc5c6f.jpg)

Dunno what this is trying to say :P

**Comment by Aspirety** [comment] 2017-06-22 11:36
If you wanna go for consistency, Meakashi's credits sequence used Bookman Old Style, and it looks fine.

**Comment by DoctorDiablo** [comment] 2017-07-06 00:26
Alright, I put together a release that includes all the TIPS and the omake sequence for this chapter.  There's no way to skip directly to them, but you can hold the Ctrl key to fast forward to them pretty quickly.

Sorry it took a bit longer than I expected, the omake was really long but I wasn't about to leave it out.

**Comment by enumag** [comment] 2017-07-06 04:51
Awesome! And I see you already started working on Kageboshi. Now I'm really hyped!

I recompiled the ADV-mode as well for anyone interested.

**Comment by enumag** [comment] 2017-07-06 09:06
@DoctorDiablo Also are all the issues reported here fixed? We could close this if that's the case.

**Comment by DoctorDiablo** [comment] 2017-07-06 17:24
Yep, that should fix all of the issues so I'm going to mark this closed.

@Aspirety feel free to re-open if there are any other issues.

**Comment by Aspirety** [comment] 2017-07-07 16:43
![](http://puu.sh/wDWRO/3f9cfc53a2.jpg)

Still getting this problem.

**Comment by enumag** [comment] 2017-07-07 16:44
Oh, forgot about that one. I'll look into it.

**Comment by Aspirety** [comment] 2017-07-07 16:47
![](http://puu.sh/wDX0J/fd56885fce.jpg)

Oh okay I guess this is happening now. Deleting compiledupdatescripts didn't seem to fix it.

**Comment by enumag** [comment] 2017-07-07 17:02
The first issue is unfixable. The function that disables screenfilter makes the select not functional too.

I can't reproduce the second issue, it works fine for me. Can I see your output_log.txt?

**Comment by Aspirety** [comment] 2017-07-07 17:15
[output_log.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1131775/output_log.txt)

**Comment by DoctorDiablo** [comment] 2017-07-07 17:20
@Aspirety Can you also post your init.txt file?

**Comment by Aspirety** [comment] 2017-07-07 17:22
[init.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1131794/init.txt)

**Comment by Aspirety** [comment] 2017-07-07 17:33
Ah, I think you're right. Can you tell me when the first TIP is meant to appear so I can check for it?

**Comment by Aspirety** [comment] 2017-07-07 17:34
Oh I found it!

**Comment by Aspirety** [comment] 2017-07-07 17:34
Why is it called "Tip 81"?

**Comment by Aspirety** [comment] 2017-07-07 17:35
Okay clicking view tip seems to have soft-locked my game. Stuck in a black screen with the cicadas in the background.

**Comment by enumag** [comment] 2017-07-07 17:41
I think it's called that way because it was the 81st tip in the console game (remember that it had multiple arcs). But maybe we should just number them from 1 for the player though even if the file names stay for us.

**Comment by Aspirety** [comment] 2017-07-07 17:45
Yeah for sure. Any idea why I'm softlocking though?

**Comment by enumag** [comment] 2017-07-07 17:48
Nope, no idea. If you give me a savefile somewhere close before the error occurs I can have a look.

**Comment by Aspirety** [comment] 2017-07-07 17:56
How do I share my savefile exactly..?

**Comment by enumag** [comment] 2017-07-07 17:58
Oh sorry. You should find them somewhere on your PC. See this page for details where to look.

https://steamcommunity.com/app/310360/discussions/0/620713633864652431/

**Comment by Aspirety** [comment] 2017-07-07 18:01
Oh i see, [here.](http://puu.sh/wDZOG/41f2db51c5.dat)

**Comment by enumag** [comment] 2017-07-07 18:17
Thanks, the problem should be fixed now.

**Comment by Aspirety** [comment] 2017-07-07 20:13
Seems to be unvoiced, is that right?

**Comment by Aspirety** [comment] 2017-07-07 20:16
I still think italics should be removed from Someutsushi ^^;

**Comment by DoctorDiablo** [comment] 2017-07-07 21:23
There should be voice acting.  If it's not there, you might not have all the new files that are in the 1.3 patch (there are a couple new sprites and backgrounds too).  Can you check if you have an s20 folder under your SE folder?

I'm thinking about removing the italics.  But should I replace them with single quotes or just remove them entirely?

**Comment by Aspirety** [comment] 2017-07-09 18:43
I'm not an expert, but I'd just go for consistency with the rest of Mangagamer's new releases.

**Comment by Aspirety** [comment] 2017-07-09 19:24
Okay, trying to skip Tip 82 seems to softlock my game. When I click Tip 83 it just skips to the next Tip instantly. When I click Tip 84 it plays a creepy effect that I'm not sure should be there, though it does belong there. The all cast review session also seems to softlock for me, sadly... Just about to record the podcast too >_<

**Comment by DoctorDiablo** [comment] 2017-07-09 21:35
Hmm... Something weird must be going on, because it didn't do anything like that for me.  I'm wondering if not all the files were updated.  Can you delete everything in your CompiledUpdateScripts folder and try again?

And if you're using saves from the previous version, there's a chance those are confusing the system.  Maybe it'll be more cooperative if you start from the beginning.

**Comment by enumag** [comment] 2017-07-09 21:37
Maybe some issue with ADV mode. If you give me your save files I can look into it.

**Comment by Aspirety** [comment] 2017-07-12 13:25
I think it's something on my end, probably didn't get all the update files. My friend was able to read the tips fine.

**Comment by DoctorDiablo** [comment] 2017-07-12 15:04
Was your friend reading in ADV mode or NVL?

**Comment by Aspirety** [comment] 2017-07-16 10:13
Now that you mention it, it was NVL (sorry for the late reply..)

[Here's a save file.](https://www.dropbox.com/s/01tmrmtgr3nt7uh/save011.dat?dl=0)

**Comment by DoctorDiablo** [comment] 2017-10-10 16:06
Marking this closed.  All the translation issues we're fixed a while back, and the ADV related issues will be addresses in the other open issue.

**Closed by DoctorDiablo** 2017-10-10 16:06 UTC
